services:
  llama-cpp:
    volumes:
      - ./llama-cpp:/data
    container_name: llama-cpp
    tty: true
    restart: unless-stopped
    image: ghcr.io/ggerganov/llama.cpp:full
    entrypoint: /data/entrypoint.sh

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llama-cpp
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'ENABLE_OLLAMA_API=false'
      - 'WEBUI_AUTH=false'
      - 'ENABLE_OAUTH_SIGNUP=false'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_OPENAI_API=true'
      - 'OPENAI_API_BASE_URL=http://llama-cpp:8081/v1'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  llama-cpp: {}
  open-webui: {}
